on: push
name: New workflow
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: install
    - name: Build
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: build
    - name: Deploy
      uses: appleboy/scp-action@v0.0.1
      env:
        HOST: ${{ secrets.HOST }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SOURCE: ./dist
        TARGET: /home/bkoshelev/tic-tac-toe_game/game
        USERNAME: ${{ secrets.USERNAME }}
      with:
        args: --debug --rm
