on: push
name: deploy admin
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
        npm install
        npm run build
      env:
        NODE_ENV: production
    - name: Rename Folder
      run: |
        mv ./dist ./tic-tac-toe_game
    - name: Deploy
      uses: appleboy/scp-action@v0.0.1
      env:
        HOST: ${{ secrets.HOST }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SOURCE: tic-tac-toe_game
        TARGET: /home/bkoshelev
        USERNAME: ${{ secrets.USERNAME }}
      with:
        args: --debug --rm
